### ISSUE TITLE
demo_gpio jtag upload  failed 

### ISSUE THREAD

**Issue by jjtoms4s** [sifive/freedom#70]
![k](https://user-images.githubusercontent.com/39576165/41222488-92c68d14-6d99-11e8-839c-74fb19641e96.jpg)
i run into this error when i upload software,does anyone knows ( i used the pre-generated mcs file to generate the hardware in fpga so the circuit is no problem )

**Comment by aignacio** [comment]
Hello @jjtoms4s, seeing your image seems that you are trying to open another instance of openocd but It's busy (because the session is still open...). Also, are you using the JTAG from OIimex as they recommend? if you are using another JTAG adapter tool, remember to change the device descriptor and the VID/PID to your correspondent tool...

**Comment by jjtoms4s** [comment]
hellow i receive the email and thanks for your reply, i ve solved this issue , just forget to close this issue
