### ISSUE TITLE
Result latency of floating point instructoins 

### ISSUE THREAD

**Issue by IC-Dream** [sifive/freedom#81]
Hi,

How much are the result latnency of floating point instructions in U54, especially, fdiv/fmul.

Thanks

**Comment by jim-wilson** [comment]
I don't know if this is documented anywhere, but if the GCC instruction scheduler can be trusted to be correct, then it is 5 cycles for FP single multiply, 7 cycles for FP double multiply, 20 cycles for FP divide, and 25 cycles for FP sqrt.

**Comment by jim-wilson** [comment]
I don't know.  I gave you all of the info I have easy access to.

**Comment by aswaterman** [comment]
Sorry the documentation's lacking in this respect.  We're working to improve it, but because we build processor generators, rather than processor instances, there's not one true answer for U54.

I believe Jim's numbers are correct for the FMA-based operations (including FMUL and FADD).  Divide/sqrt are somewhat slower than reflected in the GCC codebase.  FDIV.S and FSQRT.S are roughly 27 cycles, and FDIV.D and FSQRT.D are roughly 56 cycles.

**Comment by brucehoult** [comment]
Thanks @aswaterman, I've been wondering about these too.

Which, if any, of those block, and which can have a new instruction issued every cycle? (register availability permitting!)

**Comment by aswaterman** [comment]
div/sqrt block the whole FPU, but not the integer pipe. The FMAs are fully pipelined.
